# 8093
server:
  port: ${SERVER_PORT}
repo:
  home: ${REPO_HOME}
  
oak:
  mongo:
    db: ${DB_NAME}
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}
logging:
  level:
    web: TRACE
    org.springframework.web: TRACE
spring:
    #http:
    #    log-request-details: true
    datasource:
        url: jdbc:postgresql://localhost:5432/jcr
        username: postgres
        password: postgres
        initialization-mode: always
        initialize: true
        continue-on-error: true
kafka:
   url: http://localhost:8190/kafka/send 