# 8093
server:
  port: ${SERVER_PORT}
repo:
  home: ${REPO_HOME}
  
oak:
  mongo:
    db: ${DB_NAME}
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}
logging:
  level:
    web: TRACE
    org.springframework.web: TRACE
spring:
  http:
    log-request-details: true
